
export default [
    {
        id: 1,
        location: "Bhaisepati",
        price: "$50000",
        title: "House for rent",
        name: "sarita",
        status: "rent",
        date: "2 months ago",
    },
    {
        id: 2,
        location: "Bhaisepati",
        price: "$80000",
        title: "land for rent",
        name: "ashika",
        status: "rent",
        date: "4 weeks ago",
    },
    {
        id: 3,
        location: "Bhaisepati",
        price: "$20000",
        title: "House for sale",
        name: "samima",
        status: "sale",
        date: "1 months ago",
    },
    {
        id: 4,
        location: "Bhaisepati",
        price: "$80000",
        title: "House for sale",
        name: "sam",
        status: "sale",
        date: "3 months ago",
    },
    {
        id: 5,
        location: "kusunti",
        price: "$30000",
        title: "land for rent",
        name: "praju",
        status: "rent",
        date: "7 months ago",
    },
    {
        id: 6,
        location: "tahachal",
        price: "$70000",
        title: "land for sale",
        name: "ram",
        status: "sale",
        date: "9 months ago",
    },
    {
        id: 7,
        location: "Bhaisepati",
        price: "$900000",
        title: "House for rent",
        name: "sarita",
        status: "rent",
        date: "3 months ago",
    },
    {
        id: 8,
        location: "Bhaisepati",
        price: "$990000",
        title: "House for rent",
        name: "rina",
        status: "rent",
        date: "10 months ago",
    },

] 