export default [
    {
        id: 1,
        name: "Santosh Bist",
        location: "Eakantakuna",
        post:"CEO",
        date:"May 1, 2024",
        feedback:"hello ",
    },
    {
        id: 2,
        name: "Nabina Thapa",
        location: "Lagankhel",
        post:"Manager",
        date:"May 1, 2024",
        feedback:"hi",
    },
    {
        id: 3,
        name: "Praju dd",
        location: "Kusunti",
        post:"Manager",
        date:"May 1, 2024",
        feedback:"ro yiybcb",
    },
    {
        id: 4,
        name: "Sambhabhi Bist",
        location: "Kalanki",
        post:"Manager",
        date:"May 1, 2024",
        feedback:"wkdbsiudiebdefb ",
    },
    {
        id: 5,
        name: "Samima Miya",
        location: "Sanepa",
        post:"Manager",
        date:"May 1, 2024",
        feedback:"jediuedjenckjdb",
    },
    {
        id: 6,
        name: "Sima Thapa",
        location: "Dhobighat",
        post:"Manager",
        date:"May 1, 2024",
        feedback:"kedheifbcd",
    },
    {
        id: 7,
        name: "Ashika Paudel",
        location: "Sanepa",
        post:"Manager",
        date:"May 1, 2024",
        feedback:"ndiuewdhjbec",
    },
]